import { Property } from '@/types/property';

export const mockProperties: Property[] = [
  {
    id: '1',
    title: 'Apartamento Moderno no Centro de Curitiba',
    description: 'Lindo apartamento com acabamento de primeira, localizado em uma das regiões mais nobres de Curitiba. Próximo a shopping centers, escolas e hospitais.',
    type: 'sale',
    category: 'apartment',
    status: 'available',
    price: 850000,
    condoFee: 1200,
    iptu: 450,
    code: 'APT001',
    createdAt: '2025-01-10',
    updatedAt: '2025-01-10',
    highlighted: true,
    address: {
      street: 'Rua XV de Novembro',
      number: '1000',
      neighborhood: 'Centro',
      city: 'Curitiba',
      state: 'PR',
      zipCode: '80020-000',
    },
    features: {
      bedrooms: 3,
      bathrooms: 2,
      suites: 1,
      parkingSpaces: 2,
      area: 120,
      builtArea: 95,
    },
    amenities: {
      pool: true,
      gym: true,
      gourmetArea: true,
      elevator: true,
      balcony: true,
      security24h: true,
    },
    images: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
        order: 1,
      },
    ],
  },
  {
    id: '2',
    title: 'Casa Espaçosa no Bairro Batel',
    description: 'Casa ampla e confortável, perfeita para famílias. Com jardim e área gourmet completa.',
    type: 'sale',
    category: 'house',
    status: 'available',
    price: 1250000,
    iptu: 800,
    code: 'CAS001',
    createdAt: '2025-01-09',
    updatedAt: '2025-01-09',
    highlighted: true,
    address: {
      street: 'Rua Conselheiro Laurindo',
      number: '500',
      neighborhood: 'Batel',
      city: 'Curitiba',
      state: 'PR',
      zipCode: '80060-100',
    },
    features: {
      bedrooms: 4,
      bathrooms: 3,
      suites: 2,
      parkingSpaces: 3,
      area: 250,
      builtArea: 200,
    },
    amenities: {
      gourmetArea: true,
      garden: true,
      airConditioning: true,
      security24h: false,
    },
    images: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
        order: 1,
      },
    ],
  },
  {
    id: '3',
    title: 'Apartamento para Aluguel no Água Verde',
    description: 'Apartamento aconchegante, ideal para casal ou pequena família. Localização privilegiada.',
    type: 'rent',
    category: 'apartment',
    status: 'available',
    price: 2500,
    condoFee: 800,
    iptu: 200,
    code: 'APT002',
    createdAt: '2025-01-08',
    updatedAt: '2025-01-08',
    address: {
      street: 'Rua Coronel Dulcídio',
      number: '2000',
      neighborhood: 'Água Verde',
      city: 'Curitiba',
      state: 'PR',
      zipCode: '80250-100',
    },
    features: {
      bedrooms: 2,
      bathrooms: 1,
      suites: 0,
      parkingSpaces: 1,
      area: 75,
      builtArea: 65,
    },
    amenities: {
      pool: false,
      gym: false,
      elevator: true,
      balcony: true,
    },
    images: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
        order: 1,
      },
    ],
  },
  {
    id: '4',
    title: 'Sala Comercial no Edifício Corporate',
    description: 'Excelente sala comercial em prédio moderno. Perfeito para consultórios e escritórios.',
    type: 'rent',
    category: 'commercial',
    status: 'available',
    price: 3500,
    condoFee: 600,
    iptu: 350,
    code: 'COM001',
    createdAt: '2025-01-07',
    updatedAt: '2025-01-07',
    address: {
      street: 'Av. Cândido de Abreu',
      number: '800',
      neighborhood: 'Centro Cívico',
      city: 'Curitiba',
      state: 'PR',
      zipCode: '80530-000',
    },
    features: {
      bedrooms: 0,
      bathrooms: 2,
      suites: 0,
      parkingSpaces: 2,
      area: 80,
      builtArea: 80,
    },
    amenities: {
      elevator: true,
      airConditioning: true,
      security24h: true,
    },
    images: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
        order: 1,
      },
    ],
  },
  {
    id: '5',
    title: 'Terreno para Construção no Ecoville',
    description: 'Terreno plano e escriturado, pronto para construir. Região em expansão com ótima infraestrutura.',
    type: 'sale',
    category: 'land',
    status: 'available',
    price: 450000,
    iptu: 250,
    code: 'TER001',
    createdAt: '2025-01-06',
    updatedAt: '2025-01-06',
    address: {
      street: 'Rua Ecoville',
      number: 'S/N',
      neighborhood: 'Ecoville',
      city: 'Curitiba',
      state: 'PR',
      zipCode: '81200-000',
    },
    features: {
      bedrooms: 0,
      bathrooms: 0,
      suites: 0,
      parkingSpaces: 0,
      area: 360,
    },
    amenities: {},
    images: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800',
        order: 1,
      },
    ],
  },
  {
    id: '6',
    title: 'Cobertura Duplex com Vista Panorâmica',
    description: 'Cobertura luxuosa com vista deslumbrante. Lazer completo e alto padrão de acabamento.',
    type: 'sale',
    category: 'apartment',
    status: 'available',
    price: 2500000,
    condoFee: 2500,
    iptu: 1200,
    code: 'COB001',
    createdAt: '2025-01-05',
    updatedAt: '2025-01-05',
    highlighted: true,
    address: {
      street: 'Av. Batel',
      number: '1500',
      neighborhood: 'Batel',
      city: 'Curitiba',
      state: 'PR',
      zipCode: '80420-090',
    },
    features: {
      bedrooms: 4,
      bathrooms: 4,
      suites: 3,
      parkingSpaces: 4,
      area: 300,
      builtArea: 250,
    },
    amenities: {
      pool: true,
      gym: true,
      gourmetArea: true,
      playground: true,
      partyHall: true,
      sportsField: true,
      elevator: true,
      balcony: true,
      airConditioning: true,
      security24h: true,
    },
    images: [
      {
        id: '1',
        url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
        order: 1,
      },
    ],
  },
];
